import duckdb
import pandas as pd


# DuckDB connection
conn = duckdb.connect(":memory:")

# Stores results generated by run_sql
RESULTS = {}


def load_dataframe(df):

    if not isinstance(df, pd.DataFrame):
        raise TypeError("Expected a pandas DataFrame.")

    conn.execute("DROP TABLE IF EXISTS data")

    conn.register("temp_df", df)

    conn.execute("""
        CREATE TABLE data AS
        SELECT * FROM temp_df
    """)

    conn.unregister("temp_df")

    RESULTS.clear()

    return {
        "rows": int(len(df)),
        "columns": int(len(df.columns)),
        "column_names": list(df.columns)
    }