import duckdb
import pandas as pd


# DuckDB connection
conn = duckdb.connect(":memory:")

# Stores results generated by run_sql
RESULTS = {}


def load_dataframe(df):
    """
    Load the uploaded pandas DataFrame into DuckDB.
    """

    if not isinstance(df, pd.DataFrame):
        raise TypeError("Expected a pandas DataFrame.")

    # Remove previous registered table
    try:
        conn.unregister("data")
    except Exception:
        pass

    # Register uploaded dataframe
    conn.register("data", df)

    # Clear old query results
    RESULTS.clear()

    return {
        "rows": int(len(df)),
        "columns": int(len(df.columns)),
        "column_names": list(df.columns)
    }